<?php

namespace KRSolutions\Bundle\KRCMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * Get Category by id
     *
     * @param integer $categoryId
     *
     * @return \KRSolutions\Bundle\KRCMSBundle\Entity\Category|null
     */
    public function getCategoryById($categoryId)
    {
        $qb = $this->createQueryBuilder('categories');

        $qb->where('categories.id = :categoryId');
        $qb->setParameter('categoryId', intval($categoryId));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
